export const ADD_EMAIL = 'ADD_EMAIL'
export const REMOVE_EMAIL = 'REMOVE_EMAIL'

export const ADD_ERROR = 'ADD_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'

export const ADD_CONFIRMATION_DIALOGUE = 'ADD_CONFIRMATION_DIALOGUE'
export const REMOVE_CONFIRMATION_DIALOGUE = 'REMOVE_CONFIRMATION_DIALOGUE'

export const ADD_LOADING_REASON = 'ADD_LOADING_REASON'
export const REMOVE_LOADING_REASON = 'REMOVE_LOADING_REASON'

export const SET_USER_DATA = 'SET_USER_DATA'

export const SET_COURSES = 'SET_COURSES'
export const ADD_COURSE = 'ADD_COURSE'
export const REMOVE_COURSE = 'REMOVE_COURSE'